# Generated by Django 5.0 on 2024-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoshPuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(default='Php', max_length=10),
        ),
    ]
